# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c210641c664586cd5391480c2bd8c747401120f52025de0d4be14d9bca35cd785dd1f06a85b62223f5e8aeba650b073888d37098389bf96553ecf737fa58e88c

test:
  secret_key_base: 189cbccfd0bf71ef3bb8b6c0f3d9f79036e25700c97fcda9bfaf0f907ebebe4e65b72dbbac9b28eaf7213abba917709cabf67fd27aae3f707a17a9c4f3d5a420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
